<template><div><h1 id="根据类型统计重量接口和返回数据" tabindex="-1"><a class="header-anchor" href="#根据类型统计重量接口和返回数据" aria-hidden="true">#</a> 根据类型统计重量接口和返回数据</h1>
<h3 id="_1、实现方法" tabindex="-1"><a class="header-anchor" href="#_1、实现方法" aria-hidden="true">#</a> 1、实现方法</h3>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token annotation punctuation">@Override</span>
<span class="token keyword">public</span> <span class="token class-name">ModuleProcessingFlawResultVO</span> <span class="token function">getModuleProcessingFlawListByName</span><span class="token punctuation">(</span><span class="token class-name">ModuleProcessingFlawRespVO</span> flawRespVO<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token class-name">String</span> nameFlaw <span class="token operator">=</span> flawRespVO<span class="token punctuation">.</span><span class="token function">getFlaw</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//获取前端传回来的缺陷名称</span>
        <span class="token class-name">String</span> nameType <span class="token operator">=</span> flawRespVO<span class="token punctuation">.</span><span class="token function">getFlawType</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//类型</span>
        <span class="token class-name">LocalDateTime</span> nameDateTime <span class="token operator">=</span> flawRespVO<span class="token punctuation">.</span><span class="token function">getFlawSj</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//时间</span>
        <span class="token comment">//获取当前时间</span>
        <span class="token class-name">LocalDateTime</span> localDateTime <span class="token operator">=</span> <span class="token class-name">LocalDateTime</span><span class="token punctuation">.</span><span class="token function">now</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">//创建构造查询</span>
        <span class="token class-name">QueryWrapper</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleProcessingFlawDO</span><span class="token punctuation">></span></span> queryWrapper <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">QueryWrapper</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">//不传合金时不需要缺陷的显示</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>nameFlaw <span class="token operator">!=</span> <span class="token keyword">null</span> <span class="token operator">&amp;&amp;</span> <span class="token operator">!</span>nameFlaw<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            queryWrapper<span class="token punctuation">.</span><span class="token function">eq</span><span class="token punctuation">(</span><span class="token string">"flaw"</span><span class="token punctuation">,</span> nameFlaw<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleProcessingFlawDO</span><span class="token punctuation">></span></span> flawDOList <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ArrayList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// 根据传回的类型执行相应的查询</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token string">"本季度"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>nameType<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token comment">//对本季度做计算</span>
            <span class="token comment">// 计算本季度的开始日期和结束日期</span>
            <span class="token class-name">LocalDateTime</span> startOfQuarter <span class="token operator">=</span> localDateTime<span class="token punctuation">.</span><span class="token function">withMonth</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">(</span>localDateTime<span class="token punctuation">.</span><span class="token function">getMonthValue</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token number">3</span><span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">3</span> <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">withDayOfMonth</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">withHour</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">withMinute</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">withSecond</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token class-name">LocalDateTime</span> endOfQuarter <span class="token operator">=</span> startOfQuarter<span class="token punctuation">.</span><span class="token function">plusMonths</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">minusSeconds</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">// 清空之前的查询条件</span>
            queryWrapper<span class="token punctuation">.</span><span class="token function">clear</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">// 添加时间范围限制</span>
            queryWrapper<span class="token punctuation">.</span><span class="token function">between</span><span class="token punctuation">(</span><span class="token string">"flaw_sj"</span><span class="token punctuation">,</span> startOfQuarter<span class="token punctuation">,</span> endOfQuarter<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token string">"本年度"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>nameType<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            queryWrapper<span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span><span class="token string">"YEAR(flaw_sj) = YEAR({0})"</span><span class="token punctuation">,</span> localDateTime<span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token string">"本月"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>nameType<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            queryWrapper<span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span><span class="token string">"YEAR(flaw_sj) = YEAR({0}) AND MONTH(flaw_sj) = MONTH({0})"</span><span class="token punctuation">,</span> localDateTime<span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token punctuation">}</span>
        <span class="token comment">// TODO 添加时间范围限制</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>nameDateTime <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            queryWrapper<span class="token punctuation">.</span><span class="token function">eq</span><span class="token punctuation">(</span><span class="token string">"flaw_sj"</span><span class="token punctuation">,</span> nameDateTime<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token comment">// 执行查询</span>
        flawDOList <span class="token operator">=</span> moduleProcessingFlawMapper<span class="token punctuation">.</span><span class="token function">selectList</span><span class="token punctuation">(</span>queryWrapper<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//        // 过滤列表，仅包括特定的缺陷，并计算总的flawZzl</span>
       <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleProcessingFlawDO</span><span class="token punctuation">></span></span> filteredFlawDOList <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ArrayList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// 使用Map来跟踪不同缺陷名称的总重量</span>
        <span class="token class-name">Map</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">String</span><span class="token punctuation">,</span> <span class="token class-name">Double</span><span class="token punctuation">></span></span> totalFlawZzlMap <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">HashMap</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token class-name">ModuleProcessingFlawDO</span> flawDO <span class="token operator">:</span> flawDOList<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token class-name">String</span> flawName <span class="token operator">=</span> flawDO<span class="token punctuation">.</span><span class="token function">getFlaw</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 假设 "flaw" 是包含缺陷名称的字段</span>
            <span class="token keyword">double</span> flawZzl <span class="token operator">=</span> flawDO<span class="token punctuation">.</span><span class="token function">getFlawZzl</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 假设 "flawZzl" 是包含flawZzl值的字段</span>

            <span class="token comment">// 检查缺陷名称是否与特定的缺陷匹配</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token string">"板形不良"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>flawName<span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token string">"针孔超"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>flawName<span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token string">"厚差"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>flawName<span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token string">"杠印"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>flawName<span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token string">"辊印"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>flawName<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                totalFlawZzlMap<span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span>flawName<span class="token punctuation">,</span> totalFlawZzlMap<span class="token punctuation">.</span><span class="token function">getOrDefault</span><span class="token punctuation">(</span>flawName<span class="token punctuation">,</span> <span class="token number">0.0</span><span class="token punctuation">)</span> <span class="token operator">+</span> flawZzl<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
  
    <span class="token comment">// 将汇总的总重量排序（从大到小）</span>
    <span class="token class-name">LinkedHashMap</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">String</span><span class="token punctuation">,</span> <span class="token class-name">Double</span><span class="token punctuation">></span></span> sortedTotalFlawZzlMap <span class="token operator">=</span> totalFlawZzlMap<span class="token punctuation">.</span><span class="token function">entrySet</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">stream</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">sorted</span><span class="token punctuation">(</span><span class="token class-name">Map<span class="token punctuation">.</span>Entry</span><span class="token punctuation">.</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">String</span><span class="token punctuation">,</span> <span class="token class-name">Double</span><span class="token punctuation">></span></span><span class="token function">comparingByValue</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">reversed</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">collect</span><span class="token punctuation">(</span><span class="token class-name">Collectors</span><span class="token punctuation">.</span><span class="token function">toMap</span><span class="token punctuation">(</span><span class="token class-name">Map<span class="token punctuation">.</span>Entry</span><span class="token operator">::</span><span class="token function">getKey</span><span class="token punctuation">,</span> <span class="token class-name">Map<span class="token punctuation">.</span>Entry</span><span class="token operator">::</span><span class="token function">getValue</span><span class="token punctuation">,</span> <span class="token punctuation">(</span>e1<span class="token punctuation">,</span> e2<span class="token punctuation">)</span> <span class="token operator">-></span> e1<span class="token punctuation">,</span> <span class="token class-name">LinkedHashMap</span><span class="token operator">::</span><span class="token keyword">new</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token comment">// 将汇总的总重量赋给TotalWeight</span>
    <span class="token keyword">double</span> totalWeight <span class="token operator">=</span> sortedTotalFlawZzlMap<span class="token punctuation">.</span><span class="token function">values</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">stream</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">mapToDouble</span><span class="token punctuation">(</span><span class="token class-name">Double</span><span class="token operator">::</span><span class="token function">doubleValue</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    flawRespVO<span class="token punctuation">.</span><span class="token function">setTotalWeight</span><span class="token punctuation">(</span>totalWeight<span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token comment">// 封装结果到自定义对象</span>
    <span class="token class-name">FlawResult</span> result <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FlawResult</span><span class="token punctuation">(</span>filteredFlawDOList<span class="token punctuation">,</span> sortedTotalFlawZzlMap<span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token comment">// 返回自定义对象</span>
    <span class="token keyword">return</span> result<span class="token punctuation">;</span>

    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2、接口的代码" tabindex="-1"><a class="header-anchor" href="#_2、接口的代码" aria-hidden="true">#</a> 2、接口的代码</h3>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>改变之前
    <span class="token annotation punctuation">@GetMapping</span><span class="token punctuation">(</span><span class="token string">"/flaws"</span><span class="token punctuation">)</span>
    <span class="token annotation punctuation">@Operation</span><span class="token punctuation">(</span>summary <span class="token operator">=</span> <span class="token string">"根据缺陷名称获取数据列表"</span><span class="token punctuation">)</span>
    <span class="token annotation punctuation">@PreAuthorize</span><span class="token punctuation">(</span><span class="token string">"@ss.hasPermission('catl:module-processing-flaw:flaws')"</span><span class="token punctuation">)</span>
    <span class="token keyword">public</span> <span class="token class-name">CommonResult</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">List</span><span class="token punctuation">&lt;</span><span class="token class-name">ModuleProcessingFlawRespVO</span><span class="token punctuation">></span><span class="token punctuation">></span></span> <span class="token function">getModuleProcessingFlawListByName</span><span class="token punctuation">(</span><span class="token annotation punctuation">@Valid</span> <span class="token class-name">ModuleProcessingFlawRespVO</span> flawRespVO<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleProcessingFlawDO</span><span class="token punctuation">></span></span> list <span class="token operator">=</span> moduleProcessingFlawService<span class="token punctuation">.</span><span class="token function">getModuleProcessingFlawListByName</span><span class="token punctuation">(</span>flawRespVO<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span> <span class="token function">success</span><span class="token punctuation">(</span><span class="token class-name">ModuleProcessingFlawConvert</span><span class="token punctuation">.</span><span class="token constant">INSTANCE</span><span class="token punctuation">.</span><span class="token function">convertList</span><span class="token punctuation">(</span>list<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
改之后
    <span class="token annotation punctuation">@GetMapping</span><span class="token punctuation">(</span><span class="token string">"/flaws"</span><span class="token punctuation">)</span>
    <span class="token annotation punctuation">@Operation</span><span class="token punctuation">(</span>summary <span class="token operator">=</span> <span class="token string">"根据缺陷名称获取数据列表"</span><span class="token punctuation">)</span>
    <span class="token annotation punctuation">@PreAuthorize</span><span class="token punctuation">(</span><span class="token string">"@ss.hasPermission('catl:module-processing-flaw:flaws')"</span><span class="token punctuation">)</span>
    <span class="token keyword">public</span> <span class="token class-name">CommonResult</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleProcessingFlawResultVO</span><span class="token punctuation">></span></span> <span class="token function">getModuleProcessingFlawListByName</span><span class="token punctuation">(</span><span class="token annotation punctuation">@Valid</span> <span class="token class-name">ModuleProcessingFlawRespVO</span> flawRespVO<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token class-name">ModuleProcessingFlawResultVO</span> result <span class="token operator">=</span> moduleProcessingFlawService<span class="token punctuation">.</span><span class="token function">getModuleProcessingFlawListByName</span><span class="token punctuation">(</span>flawRespVO<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span> <span class="token function">success</span><span class="token punctuation">(</span>result<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


