<template><div><h1 id="java默认插入子表数据" tabindex="-1"><a class="header-anchor" href="#java默认插入子表数据" aria-hidden="true">#</a> Java默认插入子表数据</h1>
<h2 id="创建数据接口" tabindex="-1"><a class="header-anchor" href="#创建数据接口" aria-hidden="true">#</a> 创建数据接口</h2>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>    <span class="token annotation punctuation">@Override</span>
    <span class="token annotation punctuation">@Transactional</span><span class="token punctuation">(</span>rollbackFor <span class="token operator">=</span> <span class="token class-name">Exception</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">)</span>
    <span class="token keyword">public</span> <span class="token class-name">Long</span> <span class="token function">createModuleDetailed</span><span class="token punctuation">(</span><span class="token class-name">ModuleDetailedSaveReqVO</span> createReqVO<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// 插入</span>
        <span class="token class-name">ModuleDetailedDO</span> moduleDetailed <span class="token operator">=</span> <span class="token class-name">BeanUtils</span><span class="token punctuation">.</span><span class="token function">toBean</span><span class="token punctuation">(</span>createReqVO<span class="token punctuation">,</span> <span class="token class-name">ModuleDetailedDO</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        moduleDetailedMapper<span class="token punctuation">.</span><span class="token function">insert</span><span class="token punctuation">(</span>moduleDetailed<span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token comment">// 插入目录表</span>
        <span class="token function">createModuleDetailedDirectoryList</span><span class="token punctuation">(</span>moduleDetailed<span class="token punctuation">.</span><span class="token function">getId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> createReqVO<span class="token punctuation">.</span><span class="token function">getModuleDetailedDirectorys</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token comment">// 根据插入的 moduleDetailed ID 获取目录记录</span>
        <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleDetailedDirectoryDO</span><span class="token punctuation">></span></span> moduleDetailedDirectoryList <span class="token operator">=</span> moduleDetailedDirectoryMapper<span class="token punctuation">.</span><span class="token function">selectListByDetailedId</span><span class="token punctuation">(</span>moduleDetailed<span class="token punctuation">.</span><span class="token function">getId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token comment">// 生产记录的默认目录</span>
        <span class="token class-name">String</span><span class="token punctuation">[</span><span class="token punctuation">]</span> defaultProductionRecords <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">"熔炼记录"</span><span class="token punctuation">,</span> <span class="token string">"铸轧记录"</span><span class="token punctuation">,</span> <span class="token string">"冷轧工序"</span><span class="token punctuation">,</span> <span class="token string">"箔轧工序"</span><span class="token punctuation">,</span> <span class="token string">"分切工序"</span><span class="token punctuation">}</span><span class="token punctuation">;</span>

        <span class="token comment">// 其他类型的默认目录 (销售出口, QC, 采购&amp;进口, 原材料出入库, 成品出入库)</span>
        <span class="token class-name">String</span><span class="token punctuation">[</span><span class="token punctuation">]</span> defaultOtherRecords <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">"默认目录"</span><span class="token punctuation">}</span><span class="token punctuation">;</span>

        <span class="token comment">// 根据不同的 documentType 插入相应的默认目录</span>
        <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token class-name">ModuleDetailedDirectoryDO</span> directory <span class="token operator">:</span> moduleDetailedDirectoryList<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token class-name">String</span> documentType <span class="token operator">=</span> directory<span class="token punctuation">.</span><span class="token function">getDirectoryType</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

            <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token string">"生产记录"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>documentType<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token comment">// 插入生产记录的默认目录</span>
                <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleDetailedDocumentDO</span><span class="token punctuation">></span></span> productionDocuments <span class="token operator">=</span> <span class="token class-name">Arrays</span><span class="token punctuation">.</span><span class="token function">stream</span><span class="token punctuation">(</span>defaultProductionRecords<span class="token punctuation">)</span>
                        <span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span>record <span class="token operator">-></span> <span class="token punctuation">{</span>
                            <span class="token class-name">ModuleDetailedDocumentDO</span> document <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ModuleDetailedDocumentDO</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                            document<span class="token punctuation">.</span><span class="token function">setDirectoryId</span><span class="token punctuation">(</span>directory<span class="token punctuation">.</span><span class="token function">getId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                            document<span class="token punctuation">.</span><span class="token function">setDocumentType</span><span class="token punctuation">(</span>record<span class="token punctuation">)</span><span class="token punctuation">;</span>
                            <span class="token keyword">return</span> document<span class="token punctuation">;</span>
                        <span class="token punctuation">}</span><span class="token punctuation">)</span>
                        <span class="token punctuation">.</span><span class="token function">collect</span><span class="token punctuation">(</span><span class="token class-name">Collectors</span><span class="token punctuation">.</span><span class="token function">toList</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

                <span class="token function">createModuleDetailedDocumentList</span><span class="token punctuation">(</span>directory<span class="token punctuation">.</span><span class="token function">getId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> productionDocuments<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token class-name">Arrays</span><span class="token punctuation">.</span><span class="token function">asList</span><span class="token punctuation">(</span><span class="token string">"销售出口"</span><span class="token punctuation">,</span> <span class="token string">"QC"</span><span class="token punctuation">,</span> <span class="token string">"采购&amp;进口"</span><span class="token punctuation">,</span> <span class="token string">"原材料出入库"</span><span class="token punctuation">,</span> <span class="token string">"成品出入库"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">contains</span><span class="token punctuation">(</span>documentType<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token comment">// 插入其他类型的默认目录</span>
                <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleDetailedDocumentDO</span><span class="token punctuation">></span></span> otherDocuments <span class="token operator">=</span> <span class="token class-name">Arrays</span><span class="token punctuation">.</span><span class="token function">stream</span><span class="token punctuation">(</span>defaultOtherRecords<span class="token punctuation">)</span>
                        <span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span>record <span class="token operator">-></span> <span class="token punctuation">{</span>
                            <span class="token class-name">ModuleDetailedDocumentDO</span> document <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ModuleDetailedDocumentDO</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                            document<span class="token punctuation">.</span><span class="token function">setDirectoryId</span><span class="token punctuation">(</span>directory<span class="token punctuation">.</span><span class="token function">getId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                            document<span class="token punctuation">.</span><span class="token function">setDocumentType</span><span class="token punctuation">(</span>record<span class="token punctuation">)</span><span class="token punctuation">;</span>
                            <span class="token keyword">return</span> document<span class="token punctuation">;</span>
                        <span class="token punctuation">}</span><span class="token punctuation">)</span>
                        <span class="token punctuation">.</span><span class="token function">collect</span><span class="token punctuation">(</span><span class="token class-name">Collectors</span><span class="token punctuation">.</span><span class="token function">toList</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

                <span class="token function">createModuleDetailedDocumentList</span><span class="token punctuation">(</span>directory<span class="token punctuation">.</span><span class="token function">getId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> otherDocuments<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
                <span class="token comment">// 插入请求中的文档目录</span>
                <span class="token function">createModuleDetailedDocumentList</span><span class="token punctuation">(</span>directory<span class="token punctuation">.</span><span class="token function">getId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> createReqVO<span class="token punctuation">.</span><span class="token function">getModuleDetailedDocuments</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>

        <span class="token comment">// 返回</span>
        <span class="token keyword">return</span> moduleDetailed<span class="token punctuation">.</span><span class="token function">getId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="子表创建方法" tabindex="-1"><a class="header-anchor" href="#子表创建方法" aria-hidden="true">#</a> 子表创建方法</h2>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code> <span class="token keyword">private</span> <span class="token keyword">void</span> <span class="token function">createModuleDetailedDirectoryList</span><span class="token punctuation">(</span><span class="token class-name">Long</span> detailedId<span class="token punctuation">,</span> <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleDetailedDirectoryDO</span><span class="token punctuation">></span></span> list<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        list<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span>o <span class="token operator">-></span> o<span class="token punctuation">.</span><span class="token function">setDetailedId</span><span class="token punctuation">(</span>detailedId<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        moduleDetailedDirectoryMapper<span class="token punctuation">.</span><span class="token function">insertBatch</span><span class="token punctuation">(</span>list<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">void</span> <span class="token function">createModuleDetailedDocumentList</span><span class="token punctuation">(</span><span class="token class-name">Long</span> directoryId<span class="token punctuation">,</span> <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleDetailedDocumentDO</span><span class="token punctuation">></span></span> list<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        list<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span>o <span class="token operator">-></span> o<span class="token punctuation">.</span><span class="token function">setDirectoryId</span><span class="token punctuation">(</span>directoryId<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        moduleDetailedDocumentMapper<span class="token punctuation">.</span><span class="token function">insertBatch</span><span class="token punctuation">(</span>list<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


