export const data = JSON.parse("{\"key\":\"v-6e6ccb6b\",\"path\":\"/safety/2.html\",\"title\":\"docker安装v2rayA\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"pen-to-square\",\"date\":\"2024-06-28T00:00:00.000Z\",\"category\":[\"Linux\"],\"tag\":[\"kaliLinux\",\"V2Ray\"],\"star\":true,\"sticky\":true,\"description\":\"docker安装v2rayA Debian/Ubuntu/kaliLinux 官网：https://v2raya.org/en/ v2rayA 的功能依赖于 V2Ray 核心，因此需要安装内核。 方法一：通过软件源安装 1、公钥 wget -qO - https://apt.v2raya.org/key/public-key.asc | sudo tee /etc/apt/keyrings/v2raya.asc\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/safety/2.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"docker安装v2rayA\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"docker安装v2rayA Debian/Ubuntu/kaliLinux 官网：https://v2raya.org/en/ v2rayA 的功能依赖于 V2Ray 核心，因此需要安装内核。 方法一：通过软件源安装 1、公钥 wget -qO - https://apt.v2raya.org/key/public-key.asc | sudo tee /etc/apt/keyrings/v2raya.asc\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"蜉蝣\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"kaliLinux\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"V2Ray\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-06-28T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"docker安装v2rayA\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-06-28T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"蜉蝣\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Debian/Ubuntu/kaliLinux\",\"slug\":\"debian-ubuntu-kalilinux\",\"link\":\"#debian-ubuntu-kalilinux\",\"children\":[]}],\"readingTime\":{\"minutes\":2.86,\"words\":857},\"filePathRelative\":\"safety/2.md\",\"localizedDate\":\"2024年6月28日\",\"excerpt\":\"<h1> docker安装v2rayA</h1>\\n<h2> Debian/Ubuntu/kaliLinux</h2>\\n<p>官网：https://v2raya.org/en/</p>\\n<p>v2rayA 的功能依赖于 V2Ray 核心，因此需要安装内核。</p>\\n<h4> 方法一：通过软件源安装</h4>\\n<h5> 1、公钥</h5>\\n<div class=\\\"language-bash line-numbers-mode\\\" data-ext=\\\"sh\\\"><pre class=\\\"language-bash\\\"><code><span class=\\\"token function\\\">wget</span> <span class=\\\"token parameter variable\\\">-qO</span> - https://apt.v2raya.org/key/public-key.asc <span class=\\\"token operator\\\">|</span> <span class=\\\"token function\\\">sudo</span> <span class=\\\"token function\\\">tee</span> /etc/apt/keyrings/v2raya.asc\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
