export const data = JSON.parse("{\"key\":\"v-c3c29ed8\",\"path\":\"/posts/%E8%BD%AF%E4%BB%B6%E9%83%A8%E7%BD%B2/weave.html\",\"title\":\"weave和xxl-job-admin安装与使用\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"weave和xxl-job-admin安装与使用 一、官网 Weave Net（ https://github.com/weaveworks/weave）是Docker上的虚拟网络，可以将分布式的Docker服务链接为一个虚拟的服务网络，就像在一个局域网中运行一样，而且可以穿透防火墙（需要开放相应端口），从而可以构建出基于Mesh架构的对等服务网络(https://github.com/weaveworks/mesh )。目前Weave版本是独立发展的，尚未纳入Docker官方体系。\"},\"headers\":[{\"level\":2,\"title\":\"一、官网\",\"slug\":\"一、官网\",\"link\":\"#一、官网\",\"children\":[]},{\"level\":2,\"title\":\"二、安装\",\"slug\":\"二、安装\",\"link\":\"#二、安装\",\"children\":[{\"level\":3,\"title\":\"1、安装 Weave： 在每个宿主机上安装 Weave\",\"slug\":\"_1、安装-weave-在每个宿主机上安装-weave\",\"link\":\"#_1、安装-weave-在每个宿主机上安装-weave\",\"children\":[]}]},{\"level\":2,\"title\":\"三、安装 ping 工具：\",\"slug\":\"三、安装-ping-工具\",\"link\":\"#三、安装-ping-工具\",\"children\":[]},{\"level\":2,\"title\":\"四、安装指定版本\",\"slug\":\"四、安装指定版本\",\"link\":\"#四、安装指定版本\",\"children\":[{\"level\":3,\"title\":\"1. 确保安装了 yum-utils\",\"slug\":\"_1-确保安装了-yum-utils\",\"link\":\"#_1-确保安装了-yum-utils\",\"children\":[]},{\"level\":3,\"title\":\"2. 安装 yum-plugin-versionlock\",\"slug\":\"_2-安装-yum-plugin-versionlock\",\"link\":\"#_2-安装-yum-plugin-versionlock\",\"children\":[]},{\"level\":3,\"title\":\"3. 使用 versionlock 命令\",\"slug\":\"_3-使用-versionlock-命令\",\"link\":\"#_3-使用-versionlock-命令\",\"children\":[]},{\"level\":3,\"title\":\"4. 检查已锁定的版本\",\"slug\":\"_4-检查已锁定的版本\",\"link\":\"#_4-检查已锁定的版本\",\"children\":[]},{\"level\":3,\"title\":\"5. 解锁版本（如需）\",\"slug\":\"_5-解锁版本-如需\",\"link\":\"#_5-解锁版本-如需\",\"children\":[]},{\"level\":3,\"title\":\"6、卸载老版本\",\"slug\":\"_6、卸载老版本\",\"link\":\"#_6、卸载老版本\",\"children\":[]},{\"level\":3,\"title\":\"7、配置daemon.json\",\"slug\":\"_7、配置daemon-json\",\"link\":\"#_7、配置daemon-json\",\"children\":[]},{\"level\":3,\"title\":\"8、安装docker指定版本\",\"slug\":\"_8、安装docker指定版本\",\"link\":\"#_8、安装docker指定版本\",\"children\":[]},{\"level\":3,\"title\":\"9、启动 Docker 并启用开机自启\",\"slug\":\"_9、启动-docker-并启用开机自启\",\"link\":\"#_9、启动-docker-并启用开机自启\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.32,\"words\":697},\"filePathRelative\":\"posts/软件部署/weave.md\",\"excerpt\":\"<h1> weave和xxl-job-admin安装与使用</h1>\\n<h2> 一、<a href=\\\"https://github.com/weaveworks/weave\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">官网</a></h2>\\n<p>Weave Net（ https://github.com/weaveworks/weave）是Docker上的虚拟网络，可以将分布式的Docker服务链接为一个虚拟的服务网络，就像在一个局域网中运行一样，而且可以穿透防火墙（需要开放相应端口），从而可以构建出基于Mesh架构的对等服务网络(https://github.com/weaveworks/mesh )。目前Weave版本是独立发展的，尚未纳入Docker官方体系。</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
