export const data = JSON.parse("{\"key\":\"v-07296a04\",\"path\":\"/demo/java.html\",\"title\":\"java\",\"lang\":\"zh-CN\",\"frontmatter\":{\"category\":[\"语言\",\"Java\"],\"tag\":[\"后端\",\"java\"],\"description\":\"java 1.java中如何使用正则表达式 import java.util.regex.Pattern; import java.util.regex.Matcher; public class Regex\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/demo/java.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"java\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"java 1.java中如何使用正则表达式 import java.util.regex.Pattern; import java.util.regex.Matcher; public class Regex\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"微梦蜉蝣\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"后端\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"java\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"java\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"微梦蜉蝣\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"1.java中如何使用正则表达式\",\"slug\":\"_1-java中如何使用正则表达式\",\"link\":\"#_1-java中如何使用正则表达式\",\"children\":[]}],\"readingTime\":{\"minutes\":0.09,\"words\":28},\"filePathRelative\":\"demo/java.md\",\"excerpt\":\"<h1> java</h1>\\n<h3> 1.java中如何使用正则表达式</h3>\\n<div class=\\\"language-java line-numbers-mode\\\" data-ext=\\\"java\\\"><pre class=\\\"language-java\\\"><code><span class=\\\"token keyword\\\">import</span> <span class=\\\"token import\\\"><span class=\\\"token namespace\\\">java<span class=\\\"token punctuation\\\">.</span>util<span class=\\\"token punctuation\\\">.</span>regex<span class=\\\"token punctuation\\\">.</span></span><span class=\\\"token class-name\\\">Pattern</span></span><span class=\\\"token punctuation\\\">;</span>\\n<span class=\\\"token keyword\\\">import</span> <span class=\\\"token import\\\"><span class=\\\"token namespace\\\">java<span class=\\\"token punctuation\\\">.</span>util<span class=\\\"token punctuation\\\">.</span>regex<span class=\\\"token punctuation\\\">.</span></span><span class=\\\"token class-name\\\">Matcher</span></span><span class=\\\"token punctuation\\\">;</span>\\n<span class=\\\"token keyword\\\">public</span> <span class=\\\"token keyword\\\">class</span> <span class=\\\"token class-name\\\">Regex</span>        \\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
