<template><div><h1 id="成品去重和根据时间来查询" tabindex="-1"><a class="header-anchor" href="#成品去重和根据时间来查询" aria-hidden="true">#</a> 成品去重和根据时间来查询</h1>
<h3 id="_1、创建接口" tabindex="-1"><a class="header-anchor" href="#_1、创建接口" aria-hidden="true">#</a> 1、创建接口</h3>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token doc-comment comment">/**
     *根据前端传回来的数据进行查询并返回给前端，不传任何数据时返回全部数据
     */</span>
    <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleFinishedsDO</span><span class="token punctuation">></span></span> <span class="token function">getModuleFinishedsListName</span><span class="token punctuation">(</span><span class="token class-name">ModuleFinishedsRespVO</span> nameRespVO<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2、实现接口" tabindex="-1"><a class="header-anchor" href="#_2、实现接口" aria-hidden="true">#</a> 2、实现接口</h3>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code> <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleFinishedsDO</span><span class="token punctuation">></span></span> <span class="token function">getModuleFinishedsListName</span><span class="token punctuation">(</span><span class="token class-name">ModuleFinishedsRespVO</span> nameRespVO<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token class-name">String</span> nameBranch <span class="token operator">=</span> nameRespVO<span class="token punctuation">.</span><span class="token function">getBranch</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//接收分厂</span>
        <span class="token class-name">LocalDateTime</span> yearsDate <span class="token operator">=</span>  nameRespVO<span class="token punctuation">.</span><span class="token function">getFinishedsYears</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//接收时间</span>
        <span class="token class-name">String</span> yearsTypeName <span class="token operator">=</span> nameRespVO<span class="token punctuation">.</span><span class="token function">getYearsType</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">// 类型</span>
        <span class="token comment">//获取当前时间</span>
        <span class="token class-name">LocalDateTime</span> localDateTime <span class="token operator">=</span> <span class="token class-name">LocalDateTime</span><span class="token punctuation">.</span><span class="token function">now</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// 构建查询条件</span>
        <span class="token class-name">QueryWrapper</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleFinishedsDO</span><span class="token punctuation">></span></span> queryWrapper <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">QueryWrapper</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">//不传分厂时不需要缺陷的显示</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>nameBranch <span class="token operator">!=</span> <span class="token keyword">null</span> <span class="token operator">&amp;&amp;</span> <span class="token operator">!</span>nameBranch<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            queryWrapper<span class="token punctuation">.</span><span class="token function">eq</span><span class="token punctuation">(</span><span class="token string">"branch"</span><span class="token punctuation">,</span> nameBranch<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleFinishedsDO</span><span class="token punctuation">></span></span> yearsDOList <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ArrayList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// 根据传回的类型执行相应的查询</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token string">"本季度"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>yearsTypeName<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token comment">//对本季度做计算</span>
            <span class="token comment">// 计算本季度的开始日期和结束日期</span>
            <span class="token class-name">LocalDateTime</span> startOfQuarter <span class="token operator">=</span> localDateTime<span class="token punctuation">.</span><span class="token function">withMonth</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">(</span>localDateTime<span class="token punctuation">.</span><span class="token function">getMonthValue</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token number">3</span><span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">3</span> <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">withDayOfMonth</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">withHour</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">withMinute</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">withSecond</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token class-name">LocalDateTime</span> endOfQuarter <span class="token operator">=</span> startOfQuarter<span class="token punctuation">.</span><span class="token function">plusMonths</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">minusSeconds</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">// 清空之前的查询条件</span>
            queryWrapper<span class="token punctuation">.</span><span class="token function">clear</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">// 添加时间范围限制</span>
            queryWrapper<span class="token punctuation">.</span><span class="token function">between</span><span class="token punctuation">(</span><span class="token string">"finisheds_years"</span><span class="token punctuation">,</span> startOfQuarter<span class="token punctuation">,</span> endOfQuarter<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token string">"本年度"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>yearsTypeName<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            queryWrapper<span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span><span class="token string">"YEAR(finisheds_years) = YEAR({0})"</span><span class="token punctuation">,</span> localDateTime<span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token string">"本月"</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>yearsTypeName<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            queryWrapper<span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span><span class="token string">"YEAR(finisheds_years) = YEAR({0}) AND MONTH(finisheds_years) = MONTH({0})"</span><span class="token punctuation">,</span> localDateTime<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token comment">// TODO 添加时间范围限制</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>yearsDate <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            queryWrapper<span class="token punctuation">.</span><span class="token function">eq</span><span class="token punctuation">(</span><span class="token string">"finisheds_years"</span><span class="token punctuation">,</span> yearsDate<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token comment">// 执行查询</span>
        yearsDOList <span class="token operator">=</span> moduleFinishedsMapper<span class="token punctuation">.</span><span class="token function">selectList</span><span class="token punctuation">(</span>queryWrapper<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span> yearsDOList<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3、返回给接口" tabindex="-1"><a class="header-anchor" href="#_3、返回给接口" aria-hidden="true">#</a> 3、返回给接口</h3>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code> <span class="token annotation punctuation">@GetMapping</span><span class="token punctuation">(</span><span class="token string">"/list-name"</span><span class="token punctuation">)</span>
    <span class="token annotation punctuation">@Operation</span><span class="token punctuation">(</span>summary <span class="token operator">=</span> <span class="token string">"根据分厂名称获取数据列表"</span><span class="token punctuation">)</span>
    <span class="token annotation punctuation">@PreAuthorize</span><span class="token punctuation">(</span><span class="token string">"@ss.hasPermission('catl:module-finisheds:list-name')"</span><span class="token punctuation">)</span>
    <span class="token keyword">public</span> <span class="token class-name">CommonResult</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">List</span><span class="token punctuation">&lt;</span><span class="token class-name">ModuleFinishedsRespVO</span><span class="token punctuation">></span><span class="token punctuation">></span></span> <span class="token function">getModuleFinishedsListName</span><span class="token punctuation">(</span><span class="token annotation punctuation">@Valid</span> <span class="token class-name">ModuleFinishedsRespVO</span> nameRespVO<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ModuleFinishedsDO</span><span class="token punctuation">></span></span> list <span class="token operator">=</span> moduleFinishedsService<span class="token punctuation">.</span><span class="token function">getModuleFinishedsListName</span><span class="token punctuation">(</span>nameRespVO<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span> <span class="token function">success</span><span class="token punctuation">(</span><span class="token class-name">ModuleFinishedsConvert</span><span class="token punctuation">.</span><span class="token constant">INSTANCE</span><span class="token punctuation">.</span><span class="token function">convertList</span><span class="token punctuation">(</span>list<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


