export const data = JSON.parse("{\"key\":\"v-2fde7c19\",\"path\":\"/posts/linux%E8%BF%90%E7%BB%B4/2.html\",\"title\":\"Ubuntu 22.04 防火墙设置和开放端口命令\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"pen-to-square\",\"date\":\"2024-01-09T00:00:00.000Z\",\"category\":[\"Ubuntu22.04防火墙\"],\"tag\":[\"防火墙命令\",\"Ubuntu22.04\",\"防火墙配置\"],\"star\":true,\"sticky\":true,\"description\":\"Ubuntu 22.04 防火墙设置和开放端口命令 1、查看防火墙状态 sudo ufw status\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/posts/linux%E8%BF%90%E7%BB%B4/2.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Ubuntu 22.04 防火墙设置和开放端口命令\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Ubuntu 22.04 防火墙设置和开放端口命令 1、查看防火墙状态 sudo ufw status\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"蜉蝣\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"防火墙命令\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Ubuntu22.04\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"防火墙配置\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-01-09T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Ubuntu 22.04 防火墙设置和开放端口命令\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-01-09T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"蜉蝣\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"1、查看防火墙状态\",\"slug\":\"_1、查看防火墙状态\",\"link\":\"#_1、查看防火墙状态\",\"children\":[]},{\"level\":3,\"title\":\"2、开启防火墙\",\"slug\":\"_2、开启防火墙\",\"link\":\"#_2、开启防火墙\",\"children\":[]},{\"level\":3,\"title\":\"3、关闭防火墙\",\"slug\":\"_3、关闭防火墙\",\"link\":\"#_3、关闭防火墙\",\"children\":[]},{\"level\":3,\"title\":\"4、开放端口\",\"slug\":\"_4、开放端口\",\"link\":\"#_4、开放端口\",\"children\":[]},{\"level\":3,\"title\":\"5、查看已开放的端口\",\"slug\":\"_5、查看已开放的端口\",\"link\":\"#_5、查看已开放的端口\",\"children\":[]},{\"level\":3,\"title\":\"6、关闭已开放的端口\",\"slug\":\"_6、关闭已开放的端口\",\"link\":\"#_6、关闭已开放的端口\",\"children\":[]},{\"level\":3,\"title\":\"7、查看防火墙日志\",\"slug\":\"_7、查看防火墙日志\",\"link\":\"#_7、查看防火墙日志\",\"children\":[]},{\"level\":3,\"title\":\"8、禁止防火墙日志\",\"slug\":\"_8、禁止防火墙日志\",\"link\":\"#_8、禁止防火墙日志\",\"children\":[]}],\"readingTime\":{\"minutes\":0.47,\"words\":142},\"filePathRelative\":\"posts/linux运维/2.md\",\"localizedDate\":\"2024年1月9日\",\"excerpt\":\"<h1> Ubuntu 22.04 防火墙设置和开放端口命令</h1>\\n<h3> 1、查看防火墙状态</h3>\\n<div class=\\\"language-bash line-numbers-mode\\\" data-ext=\\\"sh\\\"><pre class=\\\"language-bash\\\"><code><span class=\\\"token function\\\">sudo</span> ufw status\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
